apiVersion: v1
kind: Service
metadata:
  labels:
    app: dudes-mealie
  name: dudes-mealie
  namespace: dudes-project
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: dudes-mealie
  type: LoadBalancer
